// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJG2Fv__tAOoJxfNqDYn0m10nQb7plIzQ',
    appId: '1:1039035121880:web:01f6521cd61a0ed9af97ad',
    messagingSenderId: '1039035121880',
    projectId: 'agiaid-iot',
    authDomain: 'agiaid-iot.firebaseapp.com',
    storageBucket: 'agiaid-iot.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX5CTJ1NWrCV7XaYqQEukedSHTXKcr9wk',
    appId: '1:1039035121880:android:92a481066ef2e125af97ad',
    messagingSenderId: '1039035121880',
    projectId: 'agiaid-iot',
    storageBucket: 'agiaid-iot.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCja_RojY6lZTSRTx4lFcmgvigg75vJ1Sk',
    appId: '1:1039035121880:ios:0eabc4b825217d9eaf97ad',
    messagingSenderId: '1039035121880',
    projectId: 'agiaid-iot',
    storageBucket: 'agiaid-iot.firebasestorage.app',
    iosBundleId: 'com.example.agriaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCja_RojY6lZTSRTx4lFcmgvigg75vJ1Sk',
    appId: '1:1039035121880:ios:0eabc4b825217d9eaf97ad',
    messagingSenderId: '1039035121880',
    projectId: 'agiaid-iot',
    storageBucket: 'agiaid-iot.firebasestorage.app',
    iosBundleId: 'com.example.agriaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJG2Fv__tAOoJxfNqDYn0m10nQb7plIzQ',
    appId: '1:1039035121880:web:e37686d7d3e59058af97ad',
    messagingSenderId: '1039035121880',
    projectId: 'agiaid-iot',
    authDomain: 'agiaid-iot.firebaseapp.com',
    storageBucket: 'agiaid-iot.firebasestorage.app',
  );
}
